# Generated by Django 5.2.14 on 2026-05-28 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=200, unique=True, verbose_name='Correo electrónico')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Contraseña Hash')),
                ('rol', models.CharField(default='USUARIO', max_length=50, verbose_name='Rol')),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='database.companiamodel', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
