# Generated by Django 6.0.5 on 2026-05-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Compañía',
                'verbose_name_plural': 'Compañías',
                'db_table': 'companias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='database.companiamodel', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
