# Generated by Django 5.2.14 on 2026-06-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_usuariomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='ciudad',
            field=models.CharField(default='Medellín', max_length=100, verbose_name='Ciudad'),
        ),
    ]
